on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  deploy:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Create Release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: true
          
      - name: Download a Build Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
            # Artifact name
          workflow: main.yml
          workflow_conclusion: success
          
      - name: Upload FileDBReader
        id: upload_reader
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./FileDBReader/FileDBReader.zip
          asset_name: FileDBReader.zip
          asset_content_type: application/zip
          
      - name: Upload FileDBSerializer
        id: upload_serializer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./FileDBReader/AnnoModsBBDom.zip
          asset_name: AnnoModsBBDom.zip
          asset_content_type: application/zip

      - name: Upload FileDBReader (Linux)
        id: upload_linux_package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./FileDBReader/FileDBReader-Linux.zip
          asset_name: FileDBReader-Linux.zip
          asset_content_type: application/zip
